### ISSUE TITLE
Add missing source information for AdMob

### ISSUE THREAD

**Issue by darek607** [Privado-Inc/SDK-Privacy-Report#13]
**Please provide information about the SDK**
Platform: Android
Name (as on the CSV file): Google AdMob

Please add this official source URL for data types collected by AdMob: https://developers.google.com/admob/android/play-data-disclosure

**Comment by vaibhavantil1** [comment]
Thanks @darek607 - This was a miss, updated. Closing this issue, feel free to add more issues and suggest improvements. Thanks.

**Comment by vaibhavantil1** [comment]
@darek607 - We have launched a free Data Safety Generator tool based on our experience so far. Would you be kind enough to test it?

Link to tool: https://github.com/Privado-Inc/privado
