### ISSUE TITLE
Update link revenuecat - spreadsheet

### ISSUE THREAD

**Issue by 123dma** [Privado-Inc/SDK-Privacy-Report#15]
Please provide information about the SDK
Name: Revenuecat 
Uses: Purchase history
Name (as on the CSV file):  Android App - SDK Privacy Report.csv

Android: https://docs.revenuecat.com/docs/google-plays-data-safety#whats-next

**Comment by vaibhavantil1** [comment]
@123dma - updated the link and values based on official documentation. Thanks for sharing 👍

**Comment by vaibhavantil1** [comment]
@123dma - We have launched a free Data Safety Generator tool based on our experience so far. Would you be kind enough to test it?

Link to tool: https://github.com/Privado-Inc/privado
