### ISSUE TITLE
Snowplow SDK request

### ISSUE THREAD

**Issue by chao2zhang** [Privado-Inc/SDK-Privacy-Report#18]
**Please provide information about the SDK**
Name: Snowplow Tracker
Uses:
Owner: Snowplow
Links to the SDK:  
This is a well-formatted table for the Google Play Data Safety https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/mobile-trackers/android-google-play-data-safety/

**Please tell us about the platforms for which the SDK exists**
[X] Android
[X] iOS

**Comment by vaibhavantil1** [comment]
Thanks @chao2zhang - I have added the information in Android report and updated.
