### ISSUE TITLE
Branch SDK request

### ISSUE THREAD

**Issue by chao2zhang** [Privado-Inc/SDK-Privacy-Report#20]
**Please provide information about the SDK**
Name: Branch
Uses:
Owner: Branch.io
Links to the SDK:
https://help.branch.io/using-branch/docs/answering-the-google-play-store-privacy-questions Branch also recently pushed a data safety section answer here.

**Please tell us about the platforms for which the SDK exists**
[X] Android
[X] iOS

**Comment by vaibhavantil1** [comment]
@chao2zhang Thanks again, added and closed the PR.

**Comment by vaibhavantil1** [comment]
@chao2zhang - We have launched a free Data Safety Generator tool based on our experience so far. Would you be kind enough to test it?

Link to tool: https://github.com/Privado-Inc/privado

**Comment by chao2zhang** [comment]
Hey @vaibhavantil1 , I can definitely try out as I have a 90% complete draft of the Google Play Safety. I will use this tool to cross-verify the answers.

**Comment by vaibhavantil1** [comment]
Awesome, @chao2zhang - This will help a lot. Look forward to your feedback!
