### ISSUE TITLE
AppCenter SDK request

### ISSUE THREAD

**Issue by Barryrowe** [Privado-Inc/SDK-Privacy-Report#27]
**Please provide information about the SDK**
Name: AppCenter
Uses: Custom Event and Usage analytics, crash reporting, custom distribution
Owner: Microsoft
Links to the SDK:
- Android https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android  
  [Github Repo](https://github.com/microsoft/appcenter-sdk-android)
- iOS https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios 
   [Github Repo](https://github.com/microsoft/appcenter-sdk-apple)

**Please tell us about the platforms for which the SDK exists**
[x] Android
[x] iOS

**Comment by vaibhavantil1** [comment]
Thanks @Barryrowe - added the information based on official FAQ docs.

**Comment by vaibhavantil1** [comment]
@Barryrowe - We have launched a free Data Safety Generator tool based on our experience so far. Would you be kind enough to test it?

Link to tool: https://github.com/Privado-Inc/privado

**Comment by tipa** [comment]
Why is the AppCenter data in the matrix declared as "shared" while Crashlytics is only declared as "collected"?
I would argue that AppCenter is a service provider that processes the data on behalf of the developer and therefore does not have to be disclosed as "shared".
