### ISSUE TITLE
Google Firebase Analytics: Missing Google Safety Section Data

### ISSUE THREAD

**Issue by vaibhavantil1** [Privado-Inc/SDK-Privacy-Report#3]
Add google safety section details for Firebase Analytics.

**Comment by sachithd** [comment]
Please add Firebase Analytics too. Thanks

**Comment by vaibhavantil1** [comment]
@sachithd - Added.

**Comment by sachithd** [comment]
Many Thanks. That was really useful. Can you please advise how best to answer the question "Do you provide a way for users to request that their data is deleted?" for 3rd party SDKs such as Firebase Analytics.

**Comment by vaibhavantil1** [comment]
@sachithd - This question is a global question and is not dependent on SDK. You can mark it yes, if users can ask you to delete all their data. All popular SDKs after GDPR have a data deletion process, here is for Analytics:

https://support.google.com/analytics/answer/9450800?hl=en
