### ISSUE TITLE
Understanding Google Play Data Safety Form Timeline  - is it safe to update apps before April without form submission?

### ISSUE THREAD

**Issue by dirkam** [Privado-Inc/SDK-Privacy-Report#30]
Hi,

I'm sorry that this is not directly related to SDKs, though this project seems to be active and it might be useful for others, too.

I'm not sure I fully understand the wording on the deadlines for the form submission. Is it safe and OK to submit an app update as of now (February) before having the form declared on Google Play? The deadline is April, that's clear. But there are wording for the February timeline updates, which makes it unclear if Google Play accepts app updates without the form submitted between February and April.

Does anyone have experience with this?

[Timeline information](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#zippy=%2Cwhat-users-will-see%2Ctimeline-information)

Thanks for this great initiative.

**Comment by vaibhavantil1** [comment]
@dirkam - I am trying at my end and will update. 

Also, to make it easier, we have launched a Data Safety Report generator. Will you be kind enough to test it and give us feedback? 

Here is the free Data Safety Generator: https://github.com/Privado-Inc/privado

**Comment by dirkam** [comment]
@vaibhavantil1 Thank you! When I'm in the process of actually putting this together, I'll definitely check this tool out.

**Comment by vaibhavantil1** [comment]
@dirkam - just submitted the app, it's under review. I will let you know once it is approved.

**Comment by dirkam** [comment]
@vaibhavantil1 is it still under review?

**Comment by vaibhavantil1** [comment]
Got approved.

**Comment by vaibhavantil1** [comment]
> @vaibhavantil1 Thank you! When I'm in the process of actually putting this together, I'll definitely check this tool out.

@dirkam - Did you get time to check out the tool? Let me know if you need any help.
