### ISSUE TITLE
SDK request -  User Messaging Platform SDK

### ISSUE THREAD

**Issue by m-melis** [Privado-Inc/SDK-Privacy-Report#34]
**Please provide information about the SDK**
Name: User Messaging Platform SDK
Owner: Google
Links to the SDK: https://developers.google.com/admob/ump/android/play-data-disclosure

**Please tell us about the platforms for which the SDK exists**
[x] Android
[x] iOS

**Comment by vaibhavantil1** [comment]
Thank, @m-melis. Added for Android. Closing this for now.
