### ISSUE TITLE
February 24 changes

### ISSUE THREAD

**Issue by dirkam** [Privado-Inc/SDK-Privacy-Report#37]
Google just introduced some changes to the Data Safety form.
Some of the data type naming is updated as well.

[February changes](https://support.google.com/googleplay/android-developer/answer/10787469#zippy=%2Cfebruary)

**Comment by vaibhavantil2** [comment]
Thanks, @dirkam - I will be updating the SDK report to these.

**Comment by vaibhavantil1** [comment]
@dirkam - Updated & Closed the issue.
